# Generated by Django 2.2.1 on 2019-08-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creat_time',
            new_name='create_time',
        ),
    ]
